title: Triple Moon Goddess â€” Dev Blog
description: Astrology infrastructure, Python, and AI-augmented engineering
theme: minima
plugins:
  - jekyll-feed
google_site_verification: Pxp5d1q4ePJSaqNyb6G4s8HM-1x2eN4UP_nGd7xyEh4
